#!/usr/bin/env bash
# Scratch TDD harness for task_027 (Generator-owned, NOT committed as part of
# the shipped test suite — Tester owns smoke-test.py test_task027_*).
# Exercises: detect_github_repo regex table (AC1/AC2), _usage_text sourcing
# safety, refresh_brain2_vibe_note idempotence + fail-soft under chmod 500.
set -uo pipefail

VIBE="/workspace/vibe"
FAIL=0
PASS=0

check() {
  local desc="$1" ok="$2" detail="${3:-}"
  if [ "$ok" = "1" ]; then
    PASS=$((PASS+1))
    # printf '  ok   %s\n' "$desc"
  else
    FAIL=$((FAIL+1))
    printf '  FAIL %s\n' "$desc"
    [ -n "$detail" ] && printf '       %s\n' "$detail"
  fi
}

# ── AC1/AC2: detect_github_repo regex table ─────────────────────────────────
echo "== detect_github_repo =="

td=$(mktemp -d)
repo="$td/repo"
mkdir -p "$repo"
(cd "$repo" && git init -q)

run_detect() {
  local url="$1"
  (cd "$repo" && git remote remove origin 2>/dev/null || true; \
   [ -n "$url" ] && git remote add origin "$url"; \
   HOME="$td/home" VIBE_SOURCE_ONLY=1 bash -c '
     source "'"$VIBE"'"
     detect_github_repo
   ')
}

expect_ok() {
  local url="$1" want="$2"
  local got rc
  got=$(run_detect "$url")
  rc=$?
  check "AC1 '$url' -> '$want'" "$([ "$rc" -eq 0 ] && [ "$got" = "$want" ] && echo 1 || echo 0)" "got='$got' rc=$rc"
}

expect_fail() {
  local url="$1" label="$2"
  local got rc
  got=$(run_detect "$url")
  rc=$?
  check "AC2 $label -> rc1/empty" "$([ "$rc" -ne 0 ] && [ -z "$got" ] && echo 1 || echo 0)" "got='$got' rc=$rc"
}

expect_ok "https://github.com/andeyePro/andeye.com.git" "andeyePro/andeye.com"
expect_ok "https://github.com/andeyePro/andeye.com" "andeyePro/andeye.com"
expect_ok "git@github.com:owner/repo.git" "owner/repo"
expect_ok "ssh://git@github.com/owner/repo.git" "owner/repo"
expect_ok "https://github.com/owner/repo.git" "owner/repo"
expect_ok "https://github.com/owner/repo/" "owner/repo"
expect_ok "https://github.com/owner/foo.git.git" "owner/foo.git"

expect_fail "" "no remote"
expect_fail "https://gitlab.com/o/r.git" "non-github remote"
expect_fail "https://github.com/owner/repo%20bad.git" "embedded %20"
expect_fail 'https://github.com/owner/repo$evil.git' "embedded \$"

rm -rf "$td"

# ── _usage_text sourcing-safe capture ───────────────────────────────────────
echo "== _usage_text (sourcing-safe) =="

td2=$(mktemp -d)
out=$(HOME="$td2/home" VIBE_CONFIG="$td2/home/.vibe/config" VIBE_SOURCE_ONLY=1 bash -c '
  source "'"$VIBE"'"
  _usage_text
')
rc=$?
check "_usage_text rc 0 when sourced (VIBE_SOURCE_ONLY=1, \$0==bash)" "$([ "$rc" -eq 0 ] && echo 1 || echo 0)"
check "_usage_text contains 'Usage:' under sourcing (not empty from wrong \$0)" "$(echo "$out" | grep -q 'Usage:' && echo 1 || echo 0)" "$(echo "$out" | head -3)"
check "_usage_text contains 'vibe pat'" "$(echo "$out" | grep -q 'vibe pat' && echo 1 || echo 0)"

# Compare byte-identical to real `vibe --help` (minus the trailing exit, which
# --help does but _usage_text doesn't call).
help_out=$(HOME="$td2/home2" VIBE_CONFIG="$td2/home2/.vibe/config" bash "$VIBE" --help)
check "_usage_text byte-identical to 'vibe --help' stdout" "$([ "$out" = "$help_out" ] && echo 1 || echo 0)" "diff:
$(diff <(echo "$out") <(echo "$help_out") | head -5)"

rm -rf "$td2"

# ── refresh_brain2_vibe_note ────────────────────────────────────────────────
echo "== refresh_brain2_vibe_note =="

td3=$(mktemp -d)
brain2="$td3/brain2"
mkdir -p "$brain2"

run_refresh() {
  local extra_env="$1"
  env $extra_env HOME="$td3/home" VIBE_SOURCE_ONLY=1 VIBE_BRAIN2_PATH="$brain2" bash -c '
    source "'"$VIBE"'"
    refresh_brain2_vibe_note
  '
}

out=$(run_refresh "")
rc=$?
note="$brain2/meta/vibe-operation.md"
check "AC3 rc 0" "$([ "$rc" -eq 0 ] && echo 1 || echo 0)"
check "AC3 note created" "$([ -f "$note" ] && echo 1 || echo 0)"
check "AC3 heading present" "$(grep -qF '# vibe — CLI operation (auto-maintained)' "$note" 2>/dev/null && echo 1 || echo 0)"
check "AC3 open marker present" "$(grep -qF '<!-- >>> vibe-cli-help (auto, do not edit) >>>' "$note" 2>/dev/null && echo 1 || echo 0)"
check "AC3 close marker present" "$(grep -qF '<!-- <<< vibe-cli-help <<< -->' "$note" 2>/dev/null && echo 1 || echo 0)"
check "AC3 Generated-by line present" "$(grep -qF 'Generated by vibe ' "$note" 2>/dev/null && echo 1 || echo 0)"
check "AC3 Usage: in note" "$(grep -qF 'Usage:' "$note" 2>/dev/null && echo 1 || echo 0)"
check "AC3 vibe pat in note" "$(grep -qF 'vibe pat' "$note" 2>/dev/null && echo 1 || echo 0)"
check "AC10 no ghp_ substring" "$(! grep -q 'ghp_' "$note" 2>/dev/null && echo 1 || echo 0)"
check "AC10 stdout empty on success" "$([ -z "$out" ] && echo 1 || echo 0)" "out='$out'"

# AC4: idempotence with pre-seeded user prose
td4=$(mktemp -d)
brain2b="$td4/brain2"
mkdir -p "$brain2b/meta"
printf '# vibe — CLI operation (auto-maintained)\n\nSome user-written prose about vibe quirks.\n' > "$brain2b/meta/vibe-operation.md"

for i in 1 2; do
  HOME="$td4/home" VIBE_SOURCE_ONLY=1 VIBE_BRAIN2_PATH="$brain2b" bash -c '
    source "'"$VIBE"'"
    refresh_brain2_vibe_note
  ' > /dev/null
  rc4=$?
  check "AC4 run $i rc 0" "$([ "$rc4" -eq 0 ] && echo 1 || echo 0)"
done
note4="$brain2b/meta/vibe-operation.md"
check "AC4 user prose intact" "$(grep -qF 'Some user-written prose about vibe quirks.' "$note4" && echo 1 || echo 0)"
open_count=$(grep -xcF '<!-- >>> vibe-cli-help (auto, do not edit) >>>' "$note4")
close_count=$(grep -xcF '<!-- <<< vibe-cli-help <<< -->' "$note4")
check "AC4 exactly one open marker (got $open_count)" "$([ "$open_count" -eq 1 ] && echo 1 || echo 0)"
check "AC4 exactly one close marker (got $close_count)" "$([ "$close_count" -eq 1 ] && echo 1 || echo 0)"

# AC5: fail-soft gating
td5=$(mktemp -d)
# VIBE_BRAIN2_PATH=off
out5a=$(HOME="$td5/home" VIBE_SOURCE_ONLY=1 VIBE_BRAIN2_PATH="off" bash -c '
  source "'"$VIBE"'"
  refresh_brain2_vibe_note
')
rc5a=$?
check "AC5 VIBE_BRAIN2_PATH=off rc 0" "$([ "$rc5a" -eq 0 ] && echo 1 || echo 0)"
check "AC5 VIBE_BRAIN2_PATH=off no file created" "$([ ! -e "$td5/home/brain2" ] && echo 1 || echo 0)"

# nonexistent dir
nonexist="$td5/does-not-exist"
out5b=$(HOME="$td5/home2" VIBE_SOURCE_ONLY=1 VIBE_BRAIN2_PATH="$nonexist" bash -c '
  source "'"$VIBE"'"
  refresh_brain2_vibe_note
')
rc5b=$?
check "AC5 nonexistent brain2 dir rc 0" "$([ "$rc5b" -eq 0 ] && echo 1 || echo 0)"
check "AC5 nonexistent brain2 dir NOT created" "$([ ! -e "$nonexist" ] && echo 1 || echo 0)"

# unwritable meta/ (chmod 500) — the set -euo pipefail survival case
brain2c="$td5/brain2c"
mkdir -p "$brain2c/meta"
chmod 500 "$brain2c/meta"
out5c=$(HOME="$td5/home3" VIBE_SOURCE_ONLY=1 VIBE_BRAIN2_PATH="$brain2c" bash -c '
  source "'"$VIBE"'"
  refresh_brain2_vibe_note
')
rc5c=$?
check "AC5 chmod-500 meta/ rc 0 (no abort under set -euo pipefail)" "$([ "$rc5c" -eq 0 ] && echo 1 || echo 0)"
check "AC5 chmod-500 meta/ no note file written" "$([ ! -e "$brain2c/meta/vibe-operation.md" ] && echo 1 || echo 0)"
chmod 700 "$brain2c/meta"

# Also test the ACTUAL call site under set -euo pipefail directly (not just
# the function in isolation) — proves `|| true` plus the internal guards
# really do prevent a hard launcher abort when meta/ is unwritable, by
# invoking the function the same way the launch path does (bare call under
# errexit, immediately after `|| true`).
brain2d="$td5/brain2d"
mkdir -p "$brain2d/meta"
chmod 500 "$brain2d/meta"
set +e
bash -c '
  set -euo pipefail
  HOME="'"$td5"'/home4"
  export HOME
  VIBE_BRAIN2_PATH="'"$brain2d"'"
  export VIBE_BRAIN2_PATH
  VIBE_SOURCE_ONLY=1
  export VIBE_SOURCE_ONLY
  source "'"$VIBE"'"
  refresh_brain2_vibe_note || true
  echo "SURVIVED"
'
rc5d=$?
set -e 2>/dev/null || true
check "AC5 errexit-shell survives call-site pattern (rc 0, prints SURVIVED)" "$([ "$rc5d" -eq 0 ] && echo 1 || echo 0)"
chmod 700 "$brain2d/meta"

rm -rf "$td3" "$td4" "$td5"

# ── AC6: launch-path wiring, anchor-pinned static check ─────────────────────
echo "== AC6 static wiring =="
gh_line=$(grep -n '^# ── GitHub setup' "$VIBE" | head -1 | cut -d: -f1)
build_line=$(grep -n '^# ── Build the image' "$VIBE" | head -1 | cut -d: -f1)
call_lines=$(grep -n 'refresh_brain2_vibe_note || true' "$VIBE" | cut -d: -f1)
call_count=$(echo "$call_lines" | grep -c .)
check "AC6 exactly one call-site line" "$([ "$call_count" -eq 1 ] && echo 1 || echo 0)" "lines: $call_lines"
call_line=$(echo "$call_lines" | head -1)
check "AC6 call line between GitHub-setup ($gh_line) and Build-the-image ($build_line) anchors" \
  "$([ "$call_line" -gt "$gh_line" ] && [ "$call_line" -lt "$build_line" ] && echo 1 || echo 0)" \
  "gh=$gh_line call=$call_line build=$build_line"

echo ""
echo "== Summary: $PASS passed, $FAIL failed =="
[ "$FAIL" -eq 0 ]
