from smoke._core import *
from smoke.checks_01_launcher_basics_and_codecheck import *
from smoke.checks_02_image_drift_and_learning import *
from smoke.checks_03_vibecopy_and_watcher import *
from smoke.checks_04_hooks_guards import *
from smoke.checks_05_numbering_hook import *
from smoke.checks_06_autoresume_and_sharedrepos import *
from smoke.checks_07_sharedrepos_cycles import *
from smoke.checks_08_credential_and_contentscan import *
from smoke.checks_09_openproject_and_scanner import *
from smoke.checks_10_pathwarn_and_hunkdiff import *
from smoke.checks_11_patrotation_and_firewall import *
from smoke.checks_12_harness_lints import *
from smoke.checks_13_spec_first import *
from smoke.checks_14_profiles import *
from smoke.checks_15_extra_domains import *
from smoke.checks_16_domain_refresh import *
from smoke.checks_17_delegation import *




def main() -> int:
    test_help()
    test_help_is_header_only()
    test_version()
    test_vibe_andeye_page_draft()
    test_repo_owner_selection()
    test_install_preflight()
    test_licence_state()
    test_env_hint_fresh()
    test_env_hint_idempotent()
    test_env_hint_preserves_user_content()
    test_docker_hints_fresh()
    test_docker_hints_heals_bool()
    test_docker_hints_respects_user_string()
    test_docker_hints_malformed_json()
    test_docker_hints_non_dict_features()
    test_install_detects_local_clone()
    test_install_falls_back_to_vibe_src()
    test_token_helpers()
    test_op_mcp_creds_lookup()
    test_code_check_json_clean_exit_and_valid_json()
    test_code_check_json_top_level_keys()
    test_code_check_json_finding_schema()
    test_code_check_json_findings_exit1_and_count()
    test_code_check_json_stdout_only_json()
    test_code_check_json_human_mode_unchanged()
    test_code_check_json_missing_shellcheck()
    test_code_check_json_help_mentions_flag()
    test_code_check_json_summary_counts()
    test_code_check_json_same_target_list()
    test_task025_ac1_git_hooks_in_default_set()
    test_task025_ac2_is_shell_script_predicate()
    test_task025_ac3_env_seam_exact_list()
    test_task025_ac4_unset_and_empty_env_falls_through_to_default()
    test_task025_ac5_real_run_green_and_larger_set()
    test_task025_ac7_no_scripts_source_text_replace()
    test_task025_ac8_code_check_py_compile()
    test_vibe_resume_args_fresh()
    test_vibe_resume_args_continue()
    test_vibe_resume_args_resume_picker()
    test_vibe_resume_args_resume_uid()
    test_vibe_is_uuid()
    test_vibe_help_mentions_continue_and_resume()
    test_parse_args_no_args()
    test_parse_args_leading_continue()
    test_parse_args_project_only()
    test_parse_args_project_then_continue()
    test_parse_args_continue_then_project()
    test_parse_args_project_then_resume_uid()
    test_parse_args_project_then_resume_picker()
    test_parse_args_project_then_rebuild()
    test_parse_args_two_positionals_rejected()
    test_parse_args_unknown_flag_rejected()
    test_parse_args_fable()
    test_parse_args_model_explicit()
    test_parse_args_model_missing_value_rejected()
    test_parse_args_model_injection_rejected()
    test_vibe_is_model_id()
    test_vibe_model_args_fresh()
    test_vibe_model_args_set()
    test_vibe_fable_billing_phase()
    test_vibe_auto_resume_helpers()
    test_vibe_auto_resume_deactivate()
    test_vibe_auto_resume_heartbeat_write()
    test_vibe_auto_resume_stalled()
    test_vibe_settings_heartbeat_hooks()
    test_vibe_supervised_launch_text()
    test_vibe_stall_watchdog_functional()
    test_vibe_gitignore_heartbeat_pattern()
    test_vibe_task016_docs()
    test_vibe_statusline()
    test_vibe_statusline_rate_limit_side_effect()
    test_vibe_auto_resume_effective_wait()
    test_vibe_help_mentions_fable_and_model()
    test_ac1_no_container()
    test_ac2_matching_image()
    test_ac3_drifted_image()
    test_ac4_remove_existing_flag_rebuild_true_drift_marker()
    test_ac4_remove_existing_flag_rebuild_true_no_drift()
    test_ac4_remove_existing_flag_no_rebuild_drift_marker()
    test_task034_linux_host()
    test_ac4_remove_existing_flag_no_rebuild_no_drift()
    test_ac5a_docker_all_fail()
    test_ac5b_ps_ok_inspect_fails()
    test_ac5c_ps_inspect_ok_tag_fails()
    test_ac5d_ps_inspect_ok_ref_inspect_fails()
    test_ac6_multiple_containers_uses_first()
    test_ac8_comment_present()
    test_learning_config_format()
    test_learning_strict_parser_no_injection()
    test_learning_init_interactive()
    test_learning_init_mkdir_offer()
    test_learning_init_reinit_path()
    test_learning_default_off_no_config()
    test_learning_learn_without_init()
    test_render_devcontainer_with_mounts_learning()
    test_learning_dispatch_no_docker_required()
    test_learning_capture_confirm_flow()
    test_learning_capture_eof_cancel()
    test_learning_capture_confirm_no()
    test_learning_public_mode_push_prompt()
    test_learning_public_mode_git_failure_survives()
    test_learning_private_mode_no_git()
    test_learning_marker_blocks_capture()
    test_learning_marker_walk_stops_at_home()
    test_learning_home_unset_fails_safe()
    test_learning_help_lists_commands()
    test_learning_banner_with_optins()
    test_learning_chmod_600_verified()
    test_learning_helpers_exist()
    test_learning_entry_path_composition()
    test_learning_format_entry()
    test_learning_commit_message()
    test_learning_config_path_helper()
    test_learning_code_check_clean()
    test_learning_short_marker_blocks()
    test_learning_exclude_creates_marker()
    test_learning_include_removes_marker()
    test_learning_exclude_refuses_in_home()
    test_learning_help_mentions_exclude_include()
    test_learning_help_says_host_only()
    test_learning_bare_learn_usage_says_host_only()
    test_learning_banner_state_three_way()
    test_learning_banner_parent_shell_load()
    test_vibe_copy_stdin_roundtrip()
    test_vibe_copy_file_arg_roundtrip()
    test_vibe_copy_scratch_file_written()
    test_vibe_copy_empty_input_stdin()
    test_vibe_copy_warn_at_8kib_plus_one()
    test_vibe_copy_refuse_at_1mib_plus_one()
    test_vibe_copy_refuses_two_args()
    test_vibe_copy_refuses_missing_file()
    test_vibe_copy_tty_absent_note()
    test_vibe_copy_scratch_failure_exits_1()
    test_c_slash_command_synced()
    test_c_slash_command_body_matches_spec()
    test_dockerfile_installs_vibe_copy()
    test_vibe_copy_watcher_noop_on_non_darwin()
    test_vibe_copy_watcher_polling_detects_change()
    test_c_preserves_user_commands()
    test_c_agents_not_touched_by_retirement()
    test_vibe_path_prefix_isolation()
    test_vibe_exit_code_propagation()
    test_task007_t1_web_research_md_exists_and_complete()
    test_task007_t2_dockerfile_copy_canonical()
    test_task007_t3_install_basics_one_fragment()
    test_task007_t4_create_from_scratch()
    test_task007_t5_idempotency()
    test_task007_t6_user_content_preserved()
    test_task007_t7_empty_source_cleanup()
    test_task007_t8_missing_source_directory()
    test_task007_t9_posix_byte_order_sort()
    test_task007_t10_agents_and_commands_still_work()
    test_task007_t11_write_env_hint_coexistence()
    test_task007_t12_fragment_removal_and_separation()
    test_task007_t13_absent_source_with_preexisting_block()
    test_task007_t14_ssh_discipline_md_exists_and_complete()
    test_learning_capture_confirm_yes_word()
    test_learning_capture_confirm_uppercase_y()
    test_learning_capture_confirm_uppercase_yes()
    test_learnings_md_fragment_present()
    test_task008_ac3_block_scoping()
    test_task008_ac11_direct_read()
    test_clipboard_drain_on_exit()
    test_task009_guard_fs_exists()
    test_task009_guard_fs_ask_fixtures()
    test_task009_guard_fs_non_learnings_fixtures()
    test_task009_guard_bash_learnings_write_fixtures()
    test_task009_guard_bash_learnings_read_fixtures()
    test_task009_guard_bash_gitpush_and_block_beats_ask()
    test_task009_settings_json_updated()
    test_task009_dockerfile_updated()
    test_task009_learn_md_exists()
    test_task009_learn_hook_md_exists()
    test_learn_docs_no_host_stage_all_footgun()
    test_task009_readme_updated()
    test_task009_code_check_clean()
    test_task009_hardening_notebookedit_not_in_matcher()
    test_zotero_guard_deny_fixtures()
    test_zotero_guard_silent_without_mount()
    test_zotero_guard_neighbour_paths_silent()
    test_zotero_guard_bash_idioms()
    test_zotero_guard_learnings_unregressed()
    test_codex_guard_fs_deny()
    test_codex_guard_bash_idioms()
    test_task009_hardening_guard_bash_set_euo()
    test_task009_hardening_guard_fs_realpath_m()
    test_task013_vs_md_intelligent_stopping()
    test_task013_vs_md_max_iter_flag()
    test_task013_no_hardcoded_cap_string()
    test_check_sp_current_exists_and_executable()
    test_check_sp_current_offline_silent()
    test_check_sp_current_fixture_no_drift()
    test_check_sp_current_fixture_missing_skill()
    test_check_sp_current_fixture_extra_skill()
    test_check_sp_current_fixture_nonexistent_errors()
    test_check_sp_current_unknown_arg_errors()
    test_check_sp_current_wired_into_container_start()
    test_sp_md_present_and_complete()
    test_sp_md_referenced_from_readme()
    test_skipped_marker_round_trip()
    test_skipped_marker_trailing_slash()
    test_skipped_marker_symlink_path()
    test_skipped_marker_writes_canonical()
    test_skipped_marker_unrelated_path_rejected()
    test_skipped_marker_back_compat_literal()
    test_check_numbering_exists_and_executable()
    test_check_numbering_silent_on_clean()
    test_check_numbering_silent_on_lettered_only()
    test_check_numbering_warns_on_mixed()
    test_check_numbering_ignores_code_fences()
    test_check_numbering_handles_missing_transcript()
    test_copy_last_block_exists_and_executable()
    test_copy_last_block_single_block()
    test_copy_last_block_language_tag()
    test_copy_last_block_multiple_blocks_last_wins()
    test_copy_last_block_no_fence_no_write()
    test_copy_last_block_no_marker_silent()
    test_copy_last_block_multiline_preserved()
    test_copy_last_block_empty_stdin()
    test_numbering_hook_readme_present()
    test_vss_md_exists_with_frontmatter()
    test_vss_md_hard_escalate_sentinels()
    test_vss_md_audit_trail_and_push_policy()
    test_todo_changelog_split()
    test_project_hygiene_fragment()
    test_install_extras_ensures_project_gitignore()
    test_feedback_auto_promote_fragment()
    test_vs_md_plain_techy_verbosity_flags()
    test_fable_subagents_flag_docs()
    test_vs_md_panel_flag()
    test_vs_md_multi_task_archive_convention()
    test_vsss_md_inherits_escalate_and_budget()
    test_vsss_persist_until_complete()
    test_vsss_fromto_format()
    test_wide_mode()
    test_install_extras_syncs_hooks()
    test_conversation_history_fragment()
    test_install_extras_ssh_discipline_opt_in()
    test_ssh_marker_fail_closed()
    test_extras_invocations_isolated()
    test_task012_review_due_banner()
    test_brain2_zotero_source_resolution()
    test_render_devcontainer_with_mounts()
    test_op_mcp_addhost_injection()
    test_build_override_config_brain2_and_zotero()
    test_install_extras_brain2_md_gated()
    test_install_extras_brain2_skills_synced()
    test_brain2_md_fragment_content()
    test_task010_smart_capture()
    test_contributor_onboarding_artifacts()

    # task_017 AC1-AC7: shared-repos
    test_task017_ac2_shared_repos_parse_valid()
    test_task017_ac2_shared_repos_parse_default_mode()
    test_task017_ac2_shared_repos_parse_comments_blanks()
    test_task017_ac2_shared_repos_parse_bad_slug()
    test_task017_ac2_shared_repos_parse_bad_mode()
    test_task017_ac2_shared_repos_parse_extra_content()
    test_task017_ac2_shared_repos_parse_missing_file()
    test_task017_ac2_shared_repos_parse_injection_strings()
    test_task017_ac2_shared_repos_parse_dot_prefix_basename_rejected()
    test_task017_ac2_repos_registry_lookup_valid()
    test_task017_ac2_repos_registry_lookup_missing_file()
    test_task017_ac2_repos_registry_lookup_bad_slug()
    test_task017_ac2_repos_registry_lookup_malformed_entry()
    test_task017_ac2_repos_registry_lookup_quote_in_path()
    test_task017_ac2_repos_registry_lookup_relative_path()
    test_task017_ac2_shared_repo_env_name_valid()
    test_task017_ac2_shared_repo_env_name_sanitisation()
    test_task017_ac2_shared_repo_env_name_collision()
    test_task017_ac2_shared_repo_ensure_signals_creates_sidecar()
    test_task017_ac2_shared_repo_ensure_signals_adds_gitignore()
    test_task017_ac2_shared_repo_ensure_signals_idempotent()
    test_task017_ac2_shared_repo_ensure_signals_unwritable_dir()
    test_task017_ac6_ensure_project_gitignore_has_vibe_signals()
    test_task017_ac1_repos_dispatch_before_parse_vibe_args()

    # task_017 Cycle 1 delta (sonnet Tester): scan state machine, ack
    # exact-pair semantics, fixed-string lookup regressions, override-JSON
    # two-bind shape, manifest filter, header case arms.
    test_task017_delta_scan_m_full_valid_chain()
    test_task017_delta_scan_n_never_registered_is_silent()
    test_task017_delta_scan_u_unacked_no_sidecar_writes()
    test_task017_delta_scan_b_path_missing()
    test_task017_delta_scan_b_token_absent()
    test_task017_delta_scan_b_sidecar_unwritable()
    test_task017_delta_scan_b_reserved_dot_prefix_basename()
    test_task017_delta_scan_b_basename_collision()
    test_task017_delta_ack_exact_pair_semantics()
    test_task017_delta_ack_idempotent_and_chmod_600()
    test_task017_delta_fixedstring_repos_registry_lookup_regex_danger()
    test_task017_delta_fixedstring_lookup_token_regex_danger()
    test_task017_delta_fixedstring_decl_remove_prefix_discipline()
    test_task017_delta_override_config_two_binds_when_acked()
    test_task017_delta_override_config_no_binds_when_unacked()
    test_task017_delta_manifest_lines_mixed_tags()
    test_task017_delta_header_case_arms_present()
    test_task017_c2_lock_acquire_writes_meta_and_holder_reads_digits()
    test_task017_c2_lock_contend_live_holder_refused_and_not_reclaimed()
    test_task017_c2_lock_stale_reclaim_dead_holder_succeeds()
    test_task017_c2_lock_release_matching_owner_removes_lock()
    test_task017_c2_lock_release_wrong_project_refused_intact()
    test_task017_c2_lock_release_wrong_pid_refused_intact()
    test_task017_c2_lock_torn_meta_never_stolen_no_crash()
    test_task017_c2_rw_free_lock_grants_rw()
    test_task017_c2_rw_contended_falls_back_ro_with_warning()
    test_task017_c2_ro_declared_never_acquires_lock()
    test_task017_c2_declaration_set_mode_flips_ro_to_rw()
    test_task017_c2_declaration_set_mode_rejects_bad_mode()
    test_task017_c2_exit_dispatcher_survives_refusing_hook()
    test_task017_c2_trap_dash_p_shows_single_dispatcher()
    test_task017_c2_no_raw_exit_trap_outside_dispatcher()
    test_task017_c2_clipboard_and_learn_tempfile_migrated_to_hooks()
    test_task017_c2_mode_coherence_rw_manifest_and_override_agree()
    test_task017_c2_repos_add_rw_flag_cli_level()

    test_task017_c3_repo_md_shape()
    test_task017_c3_statusline_structural_unchanged()
    test_task017_c3_statusline_no_signals_byte_identical()
    test_task017_c3_statusline_rw_segment_present_when_holder_and_requested()
    test_task017_c3_statusline_rw_segment_absent_when_not_holder()
    test_task017_c3_statusline_rw_segment_absent_when_no_request()
    test_task017_c3_shared_repos_md_shape()
    test_task017_c3_install_extras_shared_repos_md_gated()
    test_task017_c3_repo_claim_documented_flow_runnable()
    test_task017_c3_vibe_project_name_export_plumbing()

    # task_017 Cycle 4 (haiku Tester): credential helper never-widen attack
    # list (AC16), useHttpPath scope + functional setup-git.sh (AC17), export
    # scope + remoteEnv token/twin injection (AC18), invariant text (AC19).
    test_task017_c4_ac16_project_slug_exact_match_serves_project_token()
    test_task017_c4_ac16_shared_slug_match_with_valid_twin_serves_shared_token()
    test_task017_c4_ac16_unknown_repo_serves_nothing()
    test_task017_c4_ac16_nopath_no_shared_tokens_serves_project_token_compat()
    test_task017_c4_ac16_nopath_shared_tokens_configured_serves_nothing()
    test_task017_c4_ac16_dot_git_suffix_shared_match()
    test_task017_c4_ac16_subdir_suffix_shared_match()
    test_task017_c4_ac16_trailing_slash_only_unmatched_serves_nothing()
    test_task017_c4_ac16_trailing_slash_project_slug_still_matches()
    test_task017_c4_ac16_case_difference_project_slug_never_matches()
    test_task017_c4_ac16_traversal_segments_serve_nothing()
    test_task017_c4_ac16_embedded_control_char_serves_nothing()
    test_task017_c4_ac16_injection_string_serves_nothing_and_does_not_execute()
    test_task017_c4_ac16_sanitisation_collision_twin_mismatch_serves_nothing()
    test_task017_c4_ac16_sanitisation_collision_twin_match_serves_correct_token()
    test_task017_c4_ac16_twin_unset_serves_nothing_even_with_token_set()
    test_task017_c4_ac16_non_get_operation_serves_nothing()
    test_task017_c4_ac16_non_github_host_serves_nothing()
    test_task017_c4_ac16_lookalike_subdomain_host_serves_nothing()
    test_task017_c4_ac16_http_not_https_serves_nothing()
    test_task017_c4_ac16_empty_shared_token_never_served()
    test_task017_c4_ac16_never_widen_attack_battery()
    test_task017_c4_ac17_usehttppath_same_scope_as_helper_registration()
    test_task017_c4_ac17_setup_git_functional_in_sandbox_home()
    test_setup_git_strips_host_credential_helpers()
    test_task017_c4_ac18_top_level_exports_outside_build_override_config()
    test_task017_c4_ac18_remoteenv_shared_token_and_twin_injection()
    test_task017_c4_ac19_claude_md_invariant_text_amended()
    test_task017_c4_ac19_readme_security_section_consistent()

    # task_019 (haiku Tester): regrettable-content guard — ACs 1–17 covering
    # scanner (BLOCK/WARN tiers, secret patterns, PII rules), git hooks (staged/
    # message/push), override + allowlist + opt-out semantics, install wiring,
    # vibe audit history + staged, integration end-to-end.
    test_task019_ac1_staged_ghp_token_blocks()
    test_task019_ac2_message_private_key_blocks()
    test_task019_ac3_staged_rfc1918_ip_warns()
    test_task019_ac4_clean_diff_passes()
    test_task019_ac5_override_bypasses_and_logs()
    test_task019_ac6_allowlist_suppresses_finding()
    test_task019_ac7_guard_off_marker_skips_scan()
    test_task019_ac8_install_hooks()
    test_task019_ac9_audit_history_finds_deleted_secret()
    test_task019_ac10_real_hooks_block_commit()
    test_task019_ac11_coauthored_by_trailer_clean()
    test_task019_ac13_shellcheck_passes()
    test_task019_ac15_content_guard_md_exists()
    test_workspace_is_the_repo_fragment()
    test_task028_fragment_merges_and_fable_grant()
    test_task019_ac16_audit_history_reports_warn_pii()
    test_task019_ac17_new_branch_push_blocks_only_block_tier()
    test_prepush_no_walk_ignores_already_pushed_history()

    # task_021: commit-identity guard — scanner --identity mode, pre-commit
    # wiring, and the audit identities pass (root cause of the 2026-07-17
    # cross-org email exposure: setup-git.sh inherited the host's real email
    # and nothing checked it).
    test_task021_ac1_identity_mode_warns_on_real_email()
    test_task021_ac2_precommit_warns_on_real_email_identity()
    test_task021_ac3_audit_history_reports_identities()

    test_task020_ac1_default_opted_out()
    test_task020_ac2_global_auto_opts_in()
    test_task020_ac3_untracked_marker_opts_in()
    test_task020_ac4_committed_marker_refused()
    test_task020_ac6_non_git_workspace_refused()
    test_task020_ac5_cred_load_gated()

    # task_022: scanner match-primitive swap (bash-native [[ =~ ]], no
    # per-line subprocess forks) + --messages-stdin single-pass message scan
    # + _audit_history pass-2 rewrite. Fidelity (byte-identical findings) is
    # the security boundary; AC1 (real-history slice) and AC4 (60s timing)
    # are one-offs in the Tester's log, not permanent tests.
    test_task022_ac2_corpus_message_mode()
    test_task022_ac2_corpus_blob_stdin_mode()
    test_task022_ac2_corpus_staged_mode()
    test_task022_ac2_corpus_range_block_tier_only()
    test_task022_ac2_clean_block_no_crash()
    test_task022_ac2_allowlist_suppression()
    test_task022_ac3_messages_stdin_parity_and_attribution()
    test_task022_ac5_messages_stdin_malformed_inputs()
    test_task022_ac5_exit_codes_all_modes()
    test_task022_ac6_override_and_optout_new_primitives()
    test_task022_ac7_no_bash4_constructs()
    test_task022_ac7_no_perline_forks_in_hot_path_functions()
    test_task023_ac1_ere_allowlist_regression_with_pathwarn_lines_interspersed()
    test_task023_ac1_pathwarn_prefix_whitespace_tolerant()
    test_task023_ac2_staged_suppression_matching_vs_nonmatching()
    test_task023_ac2_nested_path_glob_crosses_slash()
    test_task023_ac2_empty_glob_no_crash_no_matchall()
    test_task023_ac3_block_fires_staged_under_pathwarn()
    test_task023_ac3_block_fires_range_under_pathwarn()
    test_task023_ac3b_no_ere_double_parse_fullline_literal()
    test_task023_ac3b_no_ere_double_parse_stripped_prefix_literal()
    test_task023_ac3c_range_idempotent_with_and_without_pathwarn()
    test_task023_ac4_message_mode_unaffected_by_pathwarn()
    test_task023_ac4_blob_stdin_unaffected_by_pathwarn()
    test_task023_ac4_messages_stdin_unaffected_by_pathwarn()
    test_task023_ac4_identity_unaffected_by_pathwarn()
    test_task023_ac5_self_clean_fixture_simulation()
    test_task023_ac7_pathwarn_functions_no_forks()
    test_task023_ac7_scan_diff_stream_still_shape_clean()
    test_task023_pathwarn_star_repo_wide_accepted()
    test_task023_glob_metachar_question_mark_semantics()

    # task_024 (sonnet Tester): hunk-aware diff parsing in scan_diff_stream
    # (--staged/--range) and scan_blob_stdin (--blob-stdin) — closes the
    # added-line header-spoof hole (AC1 skip-state, AC2 tier/file-flip, AC3
    # spoofed-content-scanned + forged-budget probe, AC3b suppressBlankEmpty
    # zero-byte context exploit, AC4 deleted/added two-line dance, AC5 real-
    # header corpus freeze, AC7 U3 context, AC8 malformed-@@ fail-safe +
    # no-fork, AC10 TODO/CHANGELOG bookkeeping). AC6's full-history
    # objective-oracle differential and AC5's spoof-free differential vs the
    # OLD scanner are one-offs in the Tester's log only.
    test_task024_ac1_spoof_neutralised_skip_state_staged()
    test_task024_ac1_spoof_neutralised_skip_state_range()
    test_task024_ac2_spoof_neutralised_tier_file_flip()
    test_task024_ac3_spoofed_content_scanned_staged()
    test_task024_ac3_spoofed_content_scanned_blob_stdin()
    test_task024_ac3b_zero_byte_context_line_suppressblankempty()
    test_task024_ac4_deleted_line_forgery_two_line_dance()
    test_task024_ac5_real_headers_corpus_frozen_findings()
    test_task024_ac7_context_lines_u3_handled_blob_stdin()
    test_task024_ac8_malformed_hunk_header_failsafe()
    test_task024_ac8_new_hunk_logic_no_forks_in_scan_blob_stdin()
    test_task024_ac10_changelog_entry_present()
    test_task024_ac10_todo_hardening_item_ticked()

    # task_026 (haiku Tester): `vibe pat [repo]` subcommand for PAT rotation +
    # launch-time 401 auto-reprompt (rotate_token, stored_token_rejected,
    # maybe_reprompt_stored_token, subcommand parsing, arg validation, help
    # text, README/MANUAL-TESTS docs)
    test_task026_ac1_arg_parsing_too_many()
    test_task026_ac1_arg_parsing_invalid_slug()
    test_task026_ac1_arg_parsing_help()
    test_task026_ac2_token_overwrite_existing()
    test_task026_ac3_empty_input_eof()
    test_task026_ac3_empty_input_newline()
    test_task026_ac4_auto_detect_repo_no_git()
    test_task026_ac4_auto_detect_repo_with_git()
    test_task026_ac5_stored_token_rejected_401()
    test_task026_ac5_stored_token_rejected_200()
    test_task026_ac5_stored_token_rejected_404_000_exit()
    test_task026_ac6_curl_arg_logging()
    test_task026_ac7_no_token_in_output()
    test_task026_ac8_maybe_reprompt_vibe_pat_check_zero()
    test_task026_ac8_maybe_reprompt_empty_token()
    test_task026_ac8_maybe_reprompt_rejected()
    test_task026_ac8_maybe_reprompt_not_rejected()
    test_task026_ac8_maybe_reprompt_placement()
    test_task026_ac9_help_mentions_pat()
    test_task026_ac9_regression_gate()
    test_task026_ac10_readme_documents_pat()
    test_task026_ac10_manual_tests_documents_pat()
    test_task026_c2_maybe_reprompt_real_setup_token_survives_closed_stdin()
    test_task026_c2_maybe_reprompt_invalid_slug_never_probes()
    test_task026_c2_pat_no_arg_refuses_invalid_detected_slug()
    test_task026_c2_rotate_token_rejects_bad_charset()

    # task_027: detect_github_repo dotted-repo fix + brain2 vibe-operation note
    test_task027_ac1_dotted_repo_https_with_git()
    test_task027_ac1_dotted_repo_https_no_git()
    test_task027_ac1_ssh_format_with_git()
    test_task027_ac1_ssh_protocol_with_git()
    test_task027_ac1_https_regression_standard_repo()
    test_task027_ac1_trailing_slash()
    test_task027_ac1_double_git_suffix()
    test_task027_ac2_no_remote()
    test_task027_ac2_non_github_remote()
    test_task027_ac2_invalid_slug()
    test_task027_ac3_brain2_creates_file_with_content()
    test_task027_ac4_idempotence_preserves_user_content()
    test_task027_ac5_fail_soft_vibe_brain2_path_off()
    test_task027_ac5_fail_soft_nonexistent_dir()
    test_task027_ac5_fail_soft_unwritable_meta()
    test_task027_ac6_anchor_placement()
    test_task027_ac7_vibe_cli_fragment_exists()
    test_task027_ac7_vibe_cli_in_glob_not_manifest()
    test_task027_ac9_readme_mentions_vibe_operation()
    test_task027_ac9_manual_tests_mentions_vibe_operation()
    test_task027_ac10_no_secrets_in_note()

    # task_028: init-firewall self-heal — retry the GitHub meta fetch, and
    # reset default policies after the flush so a closed container can rebuild
    # its own allowlist in place instead of re-failing forever.
    test_task028_ac1_source_only_no_side_effects()
    test_task028_ac2_retries_then_succeeds()
    test_task028_ac3_all_attempts_fail_returns_nonzero()
    test_gh_meta_rate_limit_and_cache_fallback()
    test_task028_ac4_no_needless_retry_on_first_success()
    test_task028_ac5_unusable_body_is_retried()
    test_task028_ac6_empty_body_is_retried()
    test_task028_ac7_fetch_has_timeouts()
    test_task028_ac8_policy_reset_after_flush()
    test_task028_ac9_still_locks_down_at_the_end()
    test_task028_ac10_changelog_entry_present()
    test_task029_default_patience()
    test_task030_mount_drift()
    test_task031_terminal_restore_and_exit_note()
    test_task014_ac1_sha1_helper()
    test_task014_ac2_bind_path_helper()
    test_task014_ac3_mkdir_before_up_static()
    test_task014_ac4_override_always_exists()
    test_task014_ac5_compose_with_learnings()
    test_task014_ac6_learning_config_absent()
    test_task014_ac6_learning_disabled()
    test_task014_ac6_no_learn_marker()
    test_task014_ac7_mount_order()
    test_task014_ac8_hash_determinism()
    test_task014_bind_dir_created()
    test_task014_ac14_no_cksum_in_builder()
    test_task014_projects_bind_mount_drift()

    # task_035: harness hygiene lints (smoke/checks_12_harness_lints.py)
    test_harness_spawns_never_inherit_stdin()
    test_harness_survives_open_stdin()
    test_no_fixed_sha_baselines()
    test_claude_md_testing_sentinels()
    test_gitignore_managed_block_and_site_gitignore()

    # task_036: /vs --spec-first flag documentation and checkpoint mechanics
    test_spec_first_flag_docs()
    # task_039's /review doc tests were defined but never registered here, so
    # they had never run; task_043 wires the gemini slot and registers both.
    test_review_command_docs()
    test_ask_command_docs()
    test_codex_container_plumbing()
    test_codex_mount_drift()
    test_codex_extra_domains()
    test_gemini_slot_wiring()
    test_codex_switch_docs()

    # task_037: /vs --TDD flag documentation and red-first trail mechanics
    test_tdd_flag_docs()

    # task_040: language-profile mechanism (`vibe --profile <name>`) + python
    test_profiles_ac2_base_dockerfile_and_devcontainer_json_untouched()
    test_profiles_ac3_help_lists_profile_flag()
    test_profiles_ac4_resolve_profile_flag_rung()
    test_profiles_ac4_resolve_profile_vibeprofile_file_rung()
    test_profiles_ac4_resolve_profile_vibe_profile_env_rung()
    test_profiles_ac4_resolve_profile_full_ladder_flag_wins()
    test_profiles_ac4_resolve_profile_none_at_each_rung()
    test_profiles_ac4_resolve_profile_trimming()
    test_profiles_ac5_profile_dir_shipped()
    test_profiles_ac5_profile_dir_custom()
    test_profiles_ac5_profile_dir_unknown_exits_1()
    test_profiles_ac5_profile_dir_shipped_beats_custom()
    test_profiles_ac6_stale_marker_missing()
    test_profiles_ac6_stale_file_newer_than_marker()
    test_profiles_ac6_stale_base_rebuilt_true()
    test_profiles_ac6_not_stale()
    test_profiles_ac7_base_is_stale_prunes_profiles()
    test_profiles_ac7_base_is_stale_when_dockerfile_newer()
    test_profiles_ac8_render_devcontainer_image_tag()
    test_profiles_ac9_python_dockerfile_literals()
    test_profiles_ac10_suggestion_fires_once_and_marks()
    test_profiles_ac10_suggestion_silent_with_no_python_files()
    test_profiles_ac10_suggestion_recognises_requirements_txt()
    test_profiles_ac11_launch_path_structure()
    test_profiles_ac12_docs()
    test_profiles_ac13_vibe_profile_gitignored()

    # task_041: per-project extra firewall domains
    test_extra_domains_ac1_untracked_file_is_read()
    test_extra_domains_ac2_config_fallback()
    test_extra_domains_ac3_file_wins_over_config()
    test_extra_domains_ac4_comments_and_blanks_ignored()
    test_extra_domains_ac5_committed_file_refused()
    test_extra_domains_ac6_non_git_workspace_refused()
    test_extra_domains_ac7_invalid_hostnames_dropped()
    test_extra_domains_ac7_valid_hostnames_accepted()
    test_extra_domains_ac7_no_shell_evaluation()
    test_extra_domains_ac8_deduped_first_seen_order()
    test_extra_domains_ac9_capped()
    test_extra_domains_ac10_firewall_optional_tier_only()
    test_extra_domains_ac11_firewall_revalidates_argv()
    test_extra_domains_ac11_argv_splits_under_script_ifs()
    test_extra_domains_ac16_crlf_file_is_accepted()
    test_extra_domains_ac16_firewall_strips_cr()
    test_extra_domains_ac17_source_attribution()
    test_extra_domains_ac17_call_site_pattern_under_set_u()
    test_extra_domains_ac17_header_never_unbound()
    test_extra_domains_ac17_launcher_uses_the_wrapper()
    test_extra_domains_ac18_drift_comparator()
    test_extra_domains_ac18_drift_wired_into_launch()
    test_extra_domains_ac12_shipped_loop_unchanged()
    test_extra_domains_ac13_devcontainer_plumbing()
    test_extra_domains_ac14_launcher_exports()
    test_extra_domains_ac15_docs()
    test_refresh_ac1_ac2_ac6_script_shape()
    test_refresh_ac3_ac4_state_file_written()
    test_refresh_ac5_dockerfile_and_sudoers()
    test_refresh_ac7_ac8_resolve_and_add()
    test_refresh_ac7_rejects_malformed_dns_answer()
    test_refresh_ac13_cap()
    test_refresh_ac9_no_state_file()
    test_refresh_ac10_missing_ipset()
    test_refresh_ac11_ac12_exit_contract()
    test_refresh_ac14_fragment_content()
    test_refresh_ac15_fragment_gated_on_extra_domains()
    test_refresh_ac17_state_file_provenance()
    test_refresh_ac18_numeric_env_validated()
    test_refresh_ac16_docs()
    test_delegate_astra_contract()
    test_delegate_failures()
    test_delegate_claude_routes()
    test_delegate_review_policy()
    test_delegate_ask_policy_and_argv()
    test_codex_dir_mode_warning()

    print()
    if FAILURES:
        print(f"✗ {len(FAILURES)} check(s) failed:")
        for name, detail in FAILURES:
            print(f"    - {name}")
            if detail:
                snippet = detail.strip().replace("\n", " | ")[:160]
                print(f"      {snippet}")
        return 1

    print("✓ smoke tests passed")
    return 0
