# AUTO-GENERATED by the Generator, task_034 cycle 1.
# Paste-ready LITERAL goldens for AC4 / AC8.
#
# Captured from the PRE-CHANGE launcher at baseline 3b23b19, BEFORE any
# source edit in this task, by sourcing `vibe` with VIBE_SOURCE_ONLY=1 under a
# Darwin `uname` PATH shim and calling render_devcontainer_with_mounts() on a
# fixed fixture input:
#     src   = devcontainer/devcontainer.json
#     mounts= /fixture/host/projects /home/node/.claude/projects 0
#             /fixture/host/brain2   /brain2                     0
#             /fixture/host/zotero   /zotero                     1
#     VIBE_OP_ADDHOST = ''  (op off)  |  'op.example.invalid'  (op on)
#
# These are NOT derived from post-change sources -- that is the whole point of
# AC4. Paste them into the smoke test as string literals; do NOT regenerate
# them from the current tree, which would make the assertion tautological.

GOLDEN_OVERRIDE_OP_OFF = '''\
{
  "name": "vibe",
  "image": "vibe-dev:latest",
  "runArgs": [
    "--cap-add=NET_ADMIN",
    "--cap-add=NET_RAW"
  ],
  "customizations": {
    "vscode": {
      "extensions": [
        "anthropic.claude-code",
        "dbaeumer.vscode-eslint",
        "esbenp.prettier-vscode",
        "eamodio.gitlens"
      ],
      "settings": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.codeActionsOnSave": {
          "source.fixAll.eslint": "explicit"
        },
        "terminal.integrated.defaultProfile.linux": "zsh",
        "terminal.integrated.profiles.linux": {
          "bash": {
            "path": "bash",
            "icon": "terminal-bash"
          },
          "zsh": {
            "path": "zsh"
          }
        }
      }
    }
  },
  "remoteUser": "node",
  "mounts": [
    "source=vibe-bash-history,target=/commandhistory,type=volume",
    "source=vibe-claude-config,target=/home/node/.claude,type=volume",
    "source=${localEnv:HOME}/.ssh,target=/home/node/.ssh-host,type=bind,readonly",
    "source=${localEnv:HOME}/.gitconfig,target=/home/node/.gitconfig-host,type=bind,readonly",
    {
      "source": "/fixture/host/projects",
      "target": "/home/node/.claude/projects",
      "type": "bind"
    },
    {
      "source": "/fixture/host/brain2",
      "target": "/brain2",
      "type": "bind"
    },
    {
      "source": "/fixture/host/zotero",
      "target": "/zotero",
      "type": "bind",
      "readonly": true
    }
  ],
  "containerEnv": {
    "NODE_OPTIONS": "--max-old-space-size=4096",
    "CLAUDE_CONFIG_DIR": "/home/node/.claude",
    "POWERLEVEL9K_DISABLE_GITSTATUS": "true",
    "VIBE_SSH_AUTO": "${localEnv:VIBE_SSH_AUTO}",
    "GIT_OPTIONAL_LOCKS": "0"
  },
  "remoteEnv": {
    "GITHUB_TOKEN": "${localEnv:GITHUB_TOKEN}",
    "VIBE_PROJECT_NAME": "${localEnv:VIBE_PROJECT_NAME}",
    "GITHUB_REPO_SLUG": "${localEnv:GITHUB_REPO_SLUG}",
    "ZOTERO_API_KEY": "${localEnv:ZOTERO_API_KEY}",
    "OPENPROJECT_MCP_URL": "${localEnv:OPENPROJECT_MCP_URL}",
    "OPENPROJECT_MCP_BEARER": "${localEnv:OPENPROJECT_MCP_BEARER}",
    "OPENPROJECT_MCP_FWD_PORT": "${localEnv:OPENPROJECT_MCP_FWD_PORT}",
    "NODE_OPTIONS": "--max-old-space-size=4096",
    "CLAUDE_CONFIG_DIR": "/home/node/.claude",
    "POWERLEVEL9K_DISABLE_GITSTATUS": "true",
    "VIBE_SSH_AUTO": "${localEnv:VIBE_SSH_AUTO}",
    "GIT_OPTIONAL_LOCKS": "0"
  },
  "workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind,consistency=delegated",
  "workspaceFolder": "/workspace",
  "postStartCommand": "sudo /usr/local/bin/init-firewall.sh && sudo /usr/sbin/avahi-daemon --daemonize --no-drop-root 2>/dev/null || true && /usr/local/bin/setup-ssh.sh && /usr/local/bin/setup-git.sh && /usr/local/bin/write-env-hint.sh && /usr/local/bin/install-claude-extras.sh && /usr/local/bin/register-op-mcp.sh",
  "waitFor": "postStartCommand"
}
'''

GOLDEN_OVERRIDE_OP_ON = '''\
{
  "name": "vibe",
  "image": "vibe-dev:latest",
  "runArgs": [
    "--cap-add=NET_ADMIN",
    "--cap-add=NET_RAW",
    "--add-host=op.example.invalid:host-gateway"
  ],
  "customizations": {
    "vscode": {
      "extensions": [
        "anthropic.claude-code",
        "dbaeumer.vscode-eslint",
        "esbenp.prettier-vscode",
        "eamodio.gitlens"
      ],
      "settings": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.codeActionsOnSave": {
          "source.fixAll.eslint": "explicit"
        },
        "terminal.integrated.defaultProfile.linux": "zsh",
        "terminal.integrated.profiles.linux": {
          "bash": {
            "path": "bash",
            "icon": "terminal-bash"
          },
          "zsh": {
            "path": "zsh"
          }
        }
      }
    }
  },
  "remoteUser": "node",
  "mounts": [
    "source=vibe-bash-history,target=/commandhistory,type=volume",
    "source=vibe-claude-config,target=/home/node/.claude,type=volume",
    "source=${localEnv:HOME}/.ssh,target=/home/node/.ssh-host,type=bind,readonly",
    "source=${localEnv:HOME}/.gitconfig,target=/home/node/.gitconfig-host,type=bind,readonly",
    {
      "source": "/fixture/host/projects",
      "target": "/home/node/.claude/projects",
      "type": "bind"
    },
    {
      "source": "/fixture/host/brain2",
      "target": "/brain2",
      "type": "bind"
    },
    {
      "source": "/fixture/host/zotero",
      "target": "/zotero",
      "type": "bind",
      "readonly": true
    }
  ],
  "containerEnv": {
    "NODE_OPTIONS": "--max-old-space-size=4096",
    "CLAUDE_CONFIG_DIR": "/home/node/.claude",
    "POWERLEVEL9K_DISABLE_GITSTATUS": "true",
    "VIBE_SSH_AUTO": "${localEnv:VIBE_SSH_AUTO}",
    "GIT_OPTIONAL_LOCKS": "0"
  },
  "remoteEnv": {
    "GITHUB_TOKEN": "${localEnv:GITHUB_TOKEN}",
    "VIBE_PROJECT_NAME": "${localEnv:VIBE_PROJECT_NAME}",
    "GITHUB_REPO_SLUG": "${localEnv:GITHUB_REPO_SLUG}",
    "ZOTERO_API_KEY": "${localEnv:ZOTERO_API_KEY}",
    "OPENPROJECT_MCP_URL": "${localEnv:OPENPROJECT_MCP_URL}",
    "OPENPROJECT_MCP_BEARER": "${localEnv:OPENPROJECT_MCP_BEARER}",
    "OPENPROJECT_MCP_FWD_PORT": "${localEnv:OPENPROJECT_MCP_FWD_PORT}",
    "NODE_OPTIONS": "--max-old-space-size=4096",
    "CLAUDE_CONFIG_DIR": "/home/node/.claude",
    "POWERLEVEL9K_DISABLE_GITSTATUS": "true",
    "VIBE_SSH_AUTO": "${localEnv:VIBE_SSH_AUTO}",
    "GIT_OPTIONAL_LOCKS": "0"
  },
  "workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind,consistency=delegated",
  "workspaceFolder": "/workspace",
  "postStartCommand": "sudo /usr/local/bin/init-firewall.sh && sudo /usr/sbin/avahi-daemon --daemonize --no-drop-root 2>/dev/null || true && /usr/local/bin/setup-ssh.sh && /usr/local/bin/setup-git.sh && /usr/local/bin/write-env-hint.sh && /usr/local/bin/install-claude-extras.sh && /usr/local/bin/register-op-mcp.sh",
  "waitFor": "postStartCommand"
}
'''

GOLDEN_INSTALL_DARWIN_OUTPUT = '''\
vibe installer

  ✗ git missing — xcode-select --install
  ✗ docker missing — brew install --cask orbstack  (or Docker Desktop: https://www.docker.com/products/docker-desktop/)
  ✗ node missing — brew install node
  ✗ devcontainer missing — npm install -g @devcontainers/cli
  ✗ gh missing — brew install gh  (then: gh auth login)

  Install the missing dependencies above, then re-run this installer.
  (A Claude Pro or Max subscription is also required to launch a session.)
EXIT=1
'''
